import {
  mdiLightbulb,
  mdiLightbulbGroup,
  mdiThermometer,
  mdiSnowflake,
  mdiFire,
  mdiBlindsHorizontal,
  mdiVideo,
  mdiLock,
  mdiLockOpen,
  mdiShieldHome,
  mdiEye,
  mdiToggleSwitch,
  mdiHome,
  mdiHomeFloor1,
  mdiCog,
  mdiWifi,
  mdiWifiOff,
  mdiAlert,
  mdiChevronLeft,
  mdiWeatherCloudy,
  mdiPower,
  mdiFan,
} from '@mdi/js';

export const DOMAIN_ICONS: Record<string, string> = {
  light: mdiLightbulb,
  climate: mdiThermometer,
  cover: mdiBlindsHorizontal,
  camera: mdiVideo,
  lock: mdiLock,
  alarm_control_panel: mdiShieldHome,
  sensor: mdiEye,
  binary_sensor: mdiEye,
  switch: mdiToggleSwitch,
  fan: mdiFan,
};

export const SIDEBAR_ICONS: Record<string, string> = {
  home: mdiHome,
  lights: mdiLightbulbGroup,
  climate: mdiThermometer,
  covers: mdiBlindsHorizontal,
  cameras: mdiVideo,
  security: mdiShieldHome,
  settings: mdiCog,
};

export const CLIMATE_MODE_ICONS: Record<string, string> = {
  heat: mdiFire,
  cool: mdiSnowflake,
  auto: mdiWeatherCloudy,
  off: mdiPower,
  fan_only: mdiFan,
};

export {
  mdiHome,
  mdiHomeFloor1,
  mdiCog,
  mdiWifi,
  mdiWifiOff,
  mdiAlert,
  mdiChevronLeft,
  mdiLightbulb,
  mdiThermometer,
  mdiBlindsHorizontal,
  mdiVideo,
  mdiLock,
  mdiLockOpen,
  mdiShieldHome,
  mdiEye,
  mdiToggleSwitch,
  mdiSnowflake,
  mdiFire,
  mdiPower,
  mdiFan,
  mdiLightbulbGroup,
};
